version: "3.7"

services:
    product-api:
        container_name: "product-api-container"
        build: './backend-product'
        depends_on: 
            - product-postgres
        ports: 
            - "3000:3000"
        environment:
            - DB_URI=product-postgres
            - CHECKOUT_URI=checkout-api
        restart: always
    
    checkout-api:
        container_name: "checkout-api-container"
        build: './backend-checkout'
        depends_on: 
            - checkout-postgres
        ports: 
            - "3001:3000"
        environment:
            - DB_URI=checkout-postgres
            - PRODUCT_URI=product-api
        restart: always
    
    product-postgres:
        container_name: product-postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5431:5432"
        volumes: 
            - ./backend-product/docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
            - POSTGRES_DB=database
        restart: always

    checkout-postgres:
        container_name: checkout-postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5433:5434"
        volumes: 
            - ./backend-checkout/docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
            - POSTGRES_DB=database
        restart: always
    