version: "3.7"

services:
    product-api:
        container_name: "product-api-container"
        image: node:10.16-slim
        working_dir: /backend/src/
        volumes:
            - ./backend-product:/backend/src/
        depends_on: 
            - product-postgres
        command: "npm run start"
        ports: 
            - "3000:3000"
        environment:
            - DB_URI=product-postgres
        restart: always
    
    checkout-api:
        container_name: "checkout-api-container"
        image: node:10.16-slim
        working_dir: /backend/src/
        volumes:
            - ./backend-checkout:/backend/src/
        command: "npm run start"
        depends_on: 
            - rabbitmq-queue
        ports: 
            - "3010:3000"
        environment:
            - PRODUCT_URI=product-api:3000
            - AUTH_URI=auth-api:3000
            - RABBITMQ_URI=rabbitmq-queue
        restart: always

    auth-api:
        container_name: "auth-api-container"
        image: node:10.16-slim
        working_dir: /backend/src/
        volumes:
            - ./backend-auth:/backend/src/
        depends_on: 
            - auth-postgres
        command: "npm run start"
        ports: 
            - "3020:3000"
        environment:
            - DB_URI=auth-postgres
        restart: always

    order-api:
        container_name: "order-api-container"
        image: node:10.16-slim
        working_dir: /backend/src/
        volumes:
            - ./backend-order:/backend/src/
        depends_on: 
            - order-postgres
            - rabbitmq-queue
        command: "npm run start"
        ports: 
            - "3030:3000"
        environment:
            - DB_URI=order-postgres
            - AUTH_URI=auth-api:3000
            - RABBITMQ_URI=rabbitmq-queue
        restart: always
        
    payment-api:
        container_name: "payment-api-container"
        image: node:10.16-slim
        working_dir: /backend/src/
        volumes:
            - ./backend-payment:/backend/src/
        command: "npm run start"
        depends_on: 
            - rabbitmq-queue
        ports: 
            - "3040:3000"
        environment:
            - AUTH_URI=auth-api:3000
            - RABBITMQ_URI=rabbitmq-queue
        restart: always
    
    product-postgres:
        container_name: product-postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5431:5432"
        volumes: 
            - ./backend-product/docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
            - POSTGRES_DB=database
        restart: always

    auth-postgres:
        container_name: auth-postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5434:5432"
        volumes: 
            - ./backend-auth/docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
            - POSTGRES_DB=database
        restart: always

    order-postgres:
        container_name: order-postgres-container
        image: library/postgres:9.6-alpine
        ports: 
            - "5435:5432"
        volumes: 
            - ./backend-order/docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root@123
            - POSTGRES_DB=database
        restart: always

    nginx:
        container_name: nginx-container
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - product-api
            - checkout-api
            - auth-api
            - order-api
    
    rabbitmq-queue:
        container_name: "rabbitmq-container"
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always